modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
issueTrackerURL="https://github.com/${sources}/issues"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
logoFile="logo.png"
logoBlur=false
authors="${mod_authors}"
description='''
${mod_description}
'''
enumExtensions="brewinandchewin_extensions.json"

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neoforge_loader_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="farmersdelight"
type="required"
versionRange="${farmers_delight_range}"
ordering="NONE"
side="BOTH"
